import JSZip from 'jszip'

export interface OutFile {
  relPath: string
  markdown: string
}

export function mdPath(relPath: string): string {
  return relPath.replace(/\.[^./]+$/, '') + '.md'
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-')
}

export function mergeWithToc(files: OutFile[], title = 'Mdify export'): string {
  const toc = files.map((f) => `- [${f.relPath}](#${slug(f.relPath)})`).join('\n')
  const body = files.map((f) => `## ${f.relPath}\n\n${f.markdown}`).join('\n\n---\n\n')
  return `# ${title}\n\n> ${files.length} files · generated by Mdify on ${new Date().toLocaleString()}\n\n## Contents\n\n${toc}\n\n---\n\n${body}\n`
}

/** What happened on a save, so the UI can show a proper receipt. */
export interface SaveReceipt {
  title: string
  count: number
  /** Full path on disk (desktop app only) — enables "Show in folder". */
  path?: string
  /** Human description of where it went. */
  where: string
}

const BROWSER_WHERE = "your browser's Downloads folder"

function browserDownload(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}

/** Returns null if the person cancelled the save dialog. */
export async function saveText(text: string, name: string): Promise<SaveReceipt | null> {
  if (window.mdify) {
    const path = await window.mdify.saveFile(name, text)
    return path ? { title: name, count: 1, path, where: path } : null
  }
  browserDownload(new Blob([text], { type: 'text/markdown;charset=utf-8' }), name)
  return { title: name, count: 1, where: BROWSER_WHERE }
}

export async function saveIndividually(files: OutFile[]): Promise<SaveReceipt | null> {
  if (window.mdify) {
    const dir = await window.mdify.pickFolder()
    if (!dir) return null
    const flat = files.map((f) => ({ relPath: mdPath(f.relPath).split('/').pop()!, content: f.markdown }))
    const { written } = await window.mdify.saveFiles(dir, flat)
    return { title: `${written} Markdown files`, count: written, path: dir, where: dir }
  }
  for (const f of files) {
    browserDownload(new Blob([f.markdown], { type: 'text/markdown;charset=utf-8' }), mdPath(f.relPath).split('/').pop()!)
    await new Promise((r) => setTimeout(r, 250))
  }
  return { title: `${files.length} Markdown files`, count: files.length, where: BROWSER_WHERE }
}

export async function saveZip(files: OutFile[], name = 'mdify-export'): Promise<SaveReceipt | null> {
  const zip = new JSZip()
  for (const f of files) zip.file(mdPath(f.relPath), f.markdown)
  const fileName = `${name}.zip`
  if (window.mdify) {
    const path = await window.mdify.saveFile(fileName, await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' }))
    return path ? { title: fileName, count: files.length, path, where: path } : null
  }
  browserDownload(await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' }), fileName)
  return { title: fileName, count: files.length, where: BROWSER_WHERE }
}

export function canPickDirectory(): boolean {
  return !!window.mdify || 'showDirectoryPicker' in window
}

type DirHandle = {
  getDirectoryHandle: (n: string, o: { create: boolean }) => Promise<DirHandle>
  getFileHandle: (n: string, o: { create: boolean }) => Promise<{ createWritable: () => Promise<{ write: (d: string) => Promise<void>; close: () => Promise<void> }> }>
}

export async function saveToFolder(files: OutFile[]): Promise<SaveReceipt | null> {
  const payload = files.map((f) => ({ relPath: mdPath(f.relPath), content: f.markdown }))
  if (window.mdify) {
    const dir = await window.mdify.pickFolder()
    if (!dir) return null
    const { written } = await window.mdify.saveFiles(dir, payload)
    return { title: `${written} Markdown files`, count: written, path: dir, where: dir }
  }
  const root = await (window as unknown as { showDirectoryPicker: (o: object) => Promise<DirHandle & { name: string }> })
    .showDirectoryPicker({ mode: 'readwrite' })
    .catch(() => null)
  if (!root) return null
  for (const f of payload) {
    const segs = f.relPath.split('/')
    let dir: DirHandle = root
    for (const s of segs.slice(0, -1)) dir = await dir.getDirectoryHandle(s, { create: true })
    const w = await (await dir.getFileHandle(segs[segs.length - 1], { create: true })).createWritable()
    await w.write(f.content)
    await w.close()
  }
  return { title: `${payload.length} Markdown files`, count: payload.length, where: `the “${root.name}” folder` }
}
