import JSZip from 'jszip'

export interface OutFile {
  relPath: string
  markdown: string
}

export function mdPath(relPath: string): string {
  return relPath.replace(/\.[^./]+$/, '') + '.md'
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-')
}

export function mergeWithToc(files: OutFile[], title = 'Mdify export'): string {
  const toc = files.map((f) => `- [${f.relPath}](#${slug(f.relPath)})`).join('\n')
  const body = files.map((f) => `## ${f.relPath}\n\n${f.markdown}`).join('\n\n---\n\n')
  return `# ${title}\n\n> ${files.length} files · generated by Mdify on ${new Date().toLocaleString()}\n\n## Contents\n\n${toc}\n\n---\n\n${body}\n`
}

export function downloadBlob(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}

export function downloadText(text: string, name: string) {
  downloadBlob(new Blob([text], { type: 'text/markdown;charset=utf-8' }), name)
}

export async function downloadIndividually(files: OutFile[]) {
  for (const f of files) {
    downloadText(f.markdown, mdPath(f.relPath).split('/').pop()!)
    await new Promise((r) => setTimeout(r, 250))
  }
}

export async function downloadZip(files: OutFile[], name = 'mdify-export') {
  const zip = new JSZip()
  for (const f of files) zip.file(mdPath(f.relPath), f.markdown)
  downloadBlob(await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' }), `${name}.zip`)
}

export function canPickDirectory(): boolean {
  return !!window.mdify || 'showDirectoryPicker' in window
}

type DirHandle = {
  getDirectoryHandle: (n: string, o: { create: boolean }) => Promise<DirHandle>
  getFileHandle: (n: string, o: { create: boolean }) => Promise<{ createWritable: () => Promise<{ write: (d: string) => Promise<void>; close: () => Promise<void> }> }>
}

export async function saveToFolder(files: OutFile[]): Promise<{ written: number; where: string } | null> {
  const payload = files.map((f) => ({ relPath: mdPath(f.relPath), content: f.markdown }))
  if (window.mdify) {
    const dir = await window.mdify.pickFolder()
    if (!dir) return null
    const { written } = await window.mdify.saveFiles(dir, payload)
    return { written, where: dir }
  }
  const root = await (window as unknown as { showDirectoryPicker: (o: object) => Promise<DirHandle & { name: string }> })
    .showDirectoryPicker({ mode: 'readwrite' })
    .catch(() => null)
  if (!root) return null
  for (const f of payload) {
    const segs = f.relPath.split('/')
    let dir: DirHandle = root
    for (const s of segs.slice(0, -1)) dir = await dir.getDirectoryHandle(s, { create: true })
    const w = await (await dir.getFileHandle(segs[segs.length - 1], { create: true })).createWritable()
    await w.write(f.content)
    await w.close()
  }
  return { written: payload.length, where: root.name }
}
